### ISSUE TITLE
Identify which initial technologies will be used in Mach-Verify

### ISSUE THREAD

**Issue by Brandon7CC** [Brandon7CC/Mach-Verify#2]
Definition of Done:

- Identified which programming language will be utilized (e.g. Python 3.9.1)
- Identified which GUI framework will be utilized (e.g. PyQt5)
- Identified which SCAT (Static Analysis Tool) will be utilized to verify standards and security at the source code level (e.g. Pylint)

**Comment by ethanasm** [comment]
- Python 3.91
- PyQt5 w/ QtGui
- Pylint, as well as Facebook's [Pysa](https://engineering.fb.com/2020/08/07/security/pysa/) for security linting
